module.exports = {
  development: {
    username: 'test',
    password: 'test',
    database: 'affiliate',
    host: '127.0.0.1',
    dialect: 'postgres',
    operatorsAliases: false,
    migrationStorage: 'json',
    migrationStoragePath: '.sequelizemeta.json',
    seederStorage: 'json',
    seederStoragePath: '.sequelizeseeddata.json',
  },
  test: {
    username: 'test',
    password: 'test',
    database: 'affiliate',
    host: '127.0.0.1',
    dialect: 'postgres',
    operatorsAliases: false,
    migrationStorage: 'json',
    migrationStoragePath: '.sequelizemeta.json',
    seederStorage: 'json',
    seederStoragePath: '.sequelizeseeddata.json',
  },
  production: {
    username: process.env.PROD_DB_USERNAME,
    password: process.env.PROD_DB_PASSWORD,
    database: 'affiliate',
    host: '127.0.0.1',
    dialect: 'postgres',
    operatorsAliases: false,
    migrationStorage: 'json',
    migrationStoragePath: '.sequelizemeta.json',
    seederStorage: 'json',
    seederStoragePath: '.sequelizeseeddata.json',
  },
}
